import { useMemo, useState } from 'react';
import { CheckCircle2 } from 'lucide-react';
import { BetaSignupStore } from '../../landing/BetaSignupStore';
import type { BetaSignupInput, SmartGlassesInterest } from '../../landing/BetaSignupTypes';
const initialInput: BetaSignupInput = { name:'', email:'', role:'', company:'', weeklyVideoCalls:5, interest:'', smartGlassesInterest:'maybe', consentBetaUpdates:false };
export function BetaSignupForm({ publicMode = true }: { publicMode?: boolean }) {
  const store=useMemo(()=>new BetaSignupStore(),[]); const [input,setInput]=useState<BetaSignupInput>(initialInput); const [status,setStatus]=useState('');
  const update=<K extends keyof BetaSignupInput>(key:K,value:BetaSignupInput[K])=>setInput(current=>({...current,[key]:value}));
  const submit=async()=>{try{store.save(input);const delivered=await fetch('/api/signup',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(input)}).then(response=>response.ok).catch(()=>false);setStatus(delivered?'Request received. We will contact selected beta participants.':'Saved locally. Online delivery is not configured yet.');setInput(initialInput)}catch(error){setStatus(error instanceof Error?error.message:'Could not save signup.')}};
  return <form onSubmit={event=>{event.preventDefault();void submit()}} className={`signup-form ${publicMode?'is-public':'panel p-5'}`}><div className="signup-field-grid"><Field label="Name" value={input.name} onChange={value=>update('name',value)} autoComplete="name"/><Field label="Email" value={input.email} onChange={value=>update('email',value)} type="email" autoComplete="email"/><Field label="Role" value={input.role} onChange={value=>update('role',value)} placeholder="Founder, recruiter, consultant..."/><Field label="Company (optional)" value={input.company??''} onChange={value=>update('company',value)} autoComplete="organization"/><label><span className="field-label">Weekly video calls</span><input className="text-input" type="number" min="0" max="100" value={input.weeklyVideoCalls} onChange={event=>update('weeklyVideoCalls',Number(event.target.value))}/></label><label><span className="field-label">Interested in smart glasses?</span><select className="text-input" value={input.smartGlassesInterest} onChange={event=>update('smartGlassesInterest',event.target.value as SmartGlassesInterest)}><option value="yes">Yes</option><option value="maybe">Maybe</option><option value="no">Not currently</option></select></label></div><label className="signup-wide-field"><span className="field-label">Why are you interested in Eidos?</span><textarea className="text-input" value={input.interest} onChange={event=>update('interest',event.target.value)}/></label><label className="signup-consent"><input type="checkbox" checked={input.consentBetaUpdates} onChange={event=>update('consentBetaUpdates',event.target.checked)}/><span>I consent to receive Eidos beta updates. I can opt out at any time.</span></label><button className="public-cta" type="submit">Join the Beta</button>{status?<p className={`signup-status ${status.startsWith('Request')?'is-success':status.startsWith('Saved')?'is-local':'is-error'}`} aria-live="polite">{status.startsWith('Request')||status.startsWith('Saved')?<CheckCircle2 size={16}/>:null}{status}</p>:null}</form>;
}
function Field({label,value,onChange,type='text',autoComplete,placeholder}:{label:string;value:string;onChange:(value:string)=>void;type?:string;autoComplete?:string;placeholder?:string}){return <label><span className="field-label">{label}</span><input className="text-input" type={type} value={value} onChange={event=>onChange(event.target.value)} autoComplete={autoComplete} placeholder={placeholder}/></label>}
