import { AnalyticsService } from '../analytics/AnalyticsService';
import { calculateBetaMetrics } from '../analytics/BetaMetrics';
import { calculateFounderLaunchMetrics } from '../analytics/FounderLaunchMetrics';
import { SessionTracker } from '../analytics/SessionTracker';
import { FeedbackService } from '../feedback/FeedbackService';
import { BetaSignupStore } from '../landing/BetaSignupStore';
import { CrashReporter } from '../analytics/CrashReporter';
import { InviteService } from '../invites/InviteService';
import { OnboardingStore } from '../onboarding/OnboardingStore';
export function FounderDashboard() {
  const analytics = new AnalyticsService(), sessions = new SessionTracker(), feedback = new FeedbackService(), signups = new BetaSignupStore(), crashes = new CrashReporter(), invites = new InviteService();
  const events = analytics.events(), sessionList = sessions.list(), responses = feedback.feedback(), pmf = feedback.pmfResponses(), codes = invites.list();
  const metrics = calculateBetaMetrics(events, sessionList), launch = calculateFounderLaunchMetrics(events, sessionList, codes.length, codes.reduce((sum, item) => sum + item.usageCount, 0), responses.length, new OnboardingStore().load());
  const betaUsers = Math.max(signups.list().length, 1), nps = responses.length ? Math.round(responses.filter((r) => r.useAgain).length / responses.length * 100) : 0, wtp = pmf.length ? Math.round(pmf.filter((r) => r.willingnessToPay !== 'no').length / pmf.length * 100) : 0, requests = topWords(responses.map((r) => r.suggestions)), bugs = topWords(responses.map((r) => r.unnatural));
  const health = Math.round(metrics.onboardingCompletionPercent * .18 + metrics.cameraOffUsagePercent * .2 + metrics.averagePresenceQuality * .2 + nps * .12 + wtp * .12 + launch.feedbackCompletionPercent * .08 + Math.min(100, 100 - crashes.list().length * 10) * .1);
  return <div className="space-y-5"><section className="founder-header"><div><p className="field-label">Founder Dashboard</p><h3>Closed beta health</h3><p>Launch, retention, trust, and presence quality from local beta exports.</p></div><strong>{health}<small>/100</small></strong></section><section className="founder-kpis">{[['Closed beta users', betaUsers], ['Daily active users', launch.dailyActiveUsers], ['Weekly active users', launch.weeklyActiveUsers], ['Retention', `${Math.round(launch.retentionPercent)}%`], ['Onboarding completion', `${Math.round(metrics.onboardingCompletionPercent)}%`], ['Voice-only adoption', `${Math.round(metrics.cameraOffUsagePercent)}%`], ['Invite conversion', `${Math.round(launch.inviteConversionPercent)}%`], ['Feedback completion', `${Math.round(launch.feedbackCompletionPercent)}%`]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><div className="grid gap-5 lg:grid-cols-2"><ListPanel title="Top feature requests" items={requests} /><ListPanel title="Most common bugs / unnatural moments" items={bugs} /></div><section className="panel p-5"><div className="grid gap-4 sm:grid-cols-4"><Metric label="Avg presence quality" value={String(Math.round(metrics.averagePresenceQuality))} /><Metric label="NPS proxy" value={String(nps)} /><Metric label="Willingness to pay" value={`${wtp}%`} /><Metric label="Crashes" value={String(crashes.list().length)} /><Metric label="Onboarding time" value={formatMinutes(launch.averageOnboardingMinutes)} /><Metric label="Installation time" value={formatMinutes(launch.averageInstallationMinutes)} /><Metric label="PMF very disappointed" value={`${pmf.length ? Math.round(pmf.filter((r) => r.disappointment === 'very').length / pmf.length * 100) : 0}%`} /><Metric label="Quality trend" value={launch.presenceQualityTrend.length ? launch.presenceQualityTrend.join(' -> ') : 'No sessions'} /></div></section></div>;
}
function topWords(values: string[]) { const phrases = values.map((v) => v.trim()).filter(Boolean); return phrases.length ? phrases.slice(-5).reverse() : ['No responses yet']; }
function ListPanel({ title, items }: { title: string; items: string[] }) { return <section className="panel p-5"><h3 className="section-title">{title}</h3><ol className="ranked-list mt-4">{items.map((item, i) => <li key={`${item}-${i}`}><span>{i + 1}</span>{item}</li>)}</ol></section>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><p>{label}</p><strong>{value}</strong></div>; }
function formatMinutes(value: number) { return value ? `${value.toFixed(1)} min` : 'Not measured'; }
