import { CheckCircle2, Download, RefreshCw, TriangleAlert, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { SystemCheckService, summarizeSystemChecks, type SystemCheckResult } from '../diagnostics/SystemCheckService';
export function SystemCheckPage({ trackerStatus }: { trackerStatus: () => { mode: string } }) {
  const service = useMemo(() => new SystemCheckService({ mediaPipeStatus: trackerStatus }), [trackerStatus]); const [results, setResults] = useState<SystemCheckResult[]>([]); const [running, setRunning] = useState(false);
  const run = async () => { setRunning(true); try { setResults(await service.run()); } finally { setRunning(false); } }; const summary = results.length ? summarizeSystemChecks(results) : undefined;
  const download = () => { const url = URL.createObjectURL(new Blob([JSON.stringify({ generatedAt: new Date().toISOString(), summary, results }, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'eidos-system-check.json'; a.click(); URL.revokeObjectURL(url); };
  return <div className="space-y-5"><section className="diagnostic-hero"><div><p className="field-label">Beta diagnostics</p><h3>Run System Check</h3><p>Verify the path from microphone to avatar output before your first meeting.</p></div>{summary ? <strong className={`diagnostic-summary is-${summary}`}>{summary}</strong> : null}</section><section className="panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="section-title">Meeting readiness</h3><p className="mt-1 text-sm text-ink/55">Checks do not record audio or video.</p></div><button className="primary-button" disabled={running} onClick={() => void run()}><RefreshCw size={17} />{running ? 'Checking...' : results.length ? 'Run again' : 'Start check'}</button></div>{results.length ? <div className="diagnostic-grid mt-5">{results.map((item) => <article className={`diagnostic-item is-${item.status}`} key={item.id}>{item.status === 'green' ? <CheckCircle2 /> : item.status === 'yellow' ? <TriangleAlert /> : <XCircle />}<div><strong>{item.label}</strong><p>{item.message}</p></div></article>)}</div> : <div className="empty-studio-state mt-5">Run the check before opening your dedicated output or joining a real meeting.</div>}<div className="mt-5 flex flex-wrap gap-2"><button className="secondary-button" disabled={!results.length} onClick={download}><Download size={16} />Export diagnostics</button><a className="secondary-button" href="mailto:support@eidospresence.com?subject=Eidos%20Beta%20Support">Contact support</a></div></section></div>;
}
