import type { AvatarAssetDescriptor } from '../AvatarAssetProvider';
import type { AvatarIdentityModel } from '../AvatarIdentityModel';
import type { PhotorealisticAvatarProvider, PhotorealisticAvatarRequest } from '../PhotorealisticAvatarGenerator';
interface ExternalAvatarResponse { avatarId:string; assetUrl:string; providerName?:string; deletionToken?:string; }
export class ExternalPhotorealProvider implements PhotorealisticAvatarProvider {
  readonly id='external-photoreal' as const; readonly displayName='External Photoreal Provider'; readonly requiresThirdPartyProcessing=true;
  readonly available:boolean;
  constructor(private readonly endpoint=import.meta.env.VITE_EIDOS_PHOTOREAL_PROVIDER_URL??'',private readonly fetcher:typeof fetch=fetch){this.available=this.isConfigured();}
  async createAvatar(request:PhotorealisticAvatarRequest):Promise<AvatarIdentityModel>{if(!this.isConfigured())throw new Error('External photoreal provider is not configured.');if(!request.consent.thirdPartyProcessing)throw new Error('Explicit third-party avatar processing consent is required.');const response=await this.fetcher(`${this.endpoint}/avatars`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({displayName:request.displayName,realismLevel:request.realismLevel,images:request.images.map(({role,mimeType,dataUrl})=>({role,mimeType,dataUrl})),permissions:{avatarCreationOnly:true,modelImprovement:false,retention:'provider-contract-required'}})});if(!response.ok)throw new Error(`Photoreal provider failed with ${response.status}.`);const result=await response.json() as ExternalAvatarResponse;const now=new Date().toISOString();return{avatarId:result.avatarId,displayName:request.displayName,sourceImages:request.consent.localStorage?request.images:request.images.map(image=>({...image,dataUrl:'',storedLocally:false})),generatedAssetUrl:result.assetUrl,provider:this.id,realismLevel:request.realismLevel,faceShapeApproximation:'unknown',skinToneApproximation:'#b98268',hairApproximation:{style:'unknown',color:'#211b19'},consentStatus:{imageProcessing:true,localStorage:request.consent.localStorage,thirdPartyProcessing:true,modelImprovement:false},createdAt:now,updatedAt:now};}
  async updateAvatar(model:AvatarIdentityModel):Promise<AvatarIdentityModel>{return{...model,updatedAt:new Date().toISOString()};}
  async deleteAvatar(model:AvatarIdentityModel):Promise<void>{if(!this.isConfigured())return;await this.fetcher(`${this.endpoint}/avatars/${encodeURIComponent(model.avatarId)}`,{method:'DELETE'});}
  async getAvatarAsset(model:AvatarIdentityModel):Promise<AvatarAssetDescriptor>{return{id:model.avatarId,provider:/\.vrm($|\?)/i.test(model.generatedAssetUrl)?'vrm':'neural-talking-head',displayName:model.displayName,skinTone:model.skinToneApproximation,hairTone:model.hairApproximation.color,jacketTone:'#24302f',shirtTone:'#e8eeeb',background:'professional-office',modelUrl:model.generatedAssetUrl,supportsBlendshapes:true,supportsRiggedBody:true};}
  status(){return{available:this.available,message:this.available?'Configured HTTPS provider; images transfer only after separate opt-in.':'Disabled until VITE_EIDOS_PHOTOREAL_PROVIDER_URL is configured and vendor review is complete.'};}
  private isConfigured(){try{const url=new URL(this.endpoint);return url.protocol==='https:';}catch{return false;}}
}